### ISSUE TITLE
local server not reponding

### ISSUE THREAD

**Issue by atgillette** [lookfirst/generator-systemjs#1]
Hi,

I'm not able to view the sample application after running "gulp run".  When loading localhost:9000, I see the status as "pending".  Any idea why the server is not serving content from "dist" folder?

**Comment by lookfirst** [comment]
Ugh. I wasn't getting notifications about new issues. Sorry!

Are you still having problems? Can you tell me anything more about your platform?

**Comment by lookfirst** [comment]
closing inactive.
