### ISSUE TITLE
option to choose between es6-seed and angular-material

### ISSUE THREAD

**Issue by DominicBoettger** [lookfirst/generator-systemjs#2]
Hello,

is it correct that there is no option to choose between the seed branch and the material branch?
Material can only installed manually, right?

Best regards
Dominic

**Comment by lookfirst** [comment]
I'm not sure I understand...

**Comment by DominicBoettger** [comment]
If i execute yo systemjs the SystemJS Seed project is getting installed and not the SystemJS Material Start ES6.

The description says:
This project is the generator for the SystemJS Seed project and SystemJS Material Start ES6 project.

**Comment by lookfirst** [comment]
They are two separate projects which are built using this project. I hope that clarifies things.
